### ISSUE TITLE
hamburger menu does nothing

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1374] opened 2019-06-25 20:20 UTC
In narrow mode a hamburger menu appears but hitting it doesn't do anything for me

![image](https://user-images.githubusercontent.com/203523/60130400-23d28100-9765-11e9-9dbe-dbb1b76a30ac.png)

**Comment by nicolaskruchten** [comment] 2019-06-25 20:20
I vote we just drop it.

**Comment by cldougl** [comment] 2019-06-25 20:53
Is this a duplicate of https://github.com/plotly/documentation/issues/1342 (cc @michaelbabyn )?
I'm 100% ok w/ dropping it.

**Comment by michaelbabyn** [comment] 2019-06-25 20:56
Yeah, it's a duplicate.

**Comment by cldougl** [comment] 2019-06-26 15:17
closing in favor of https://github.com/plotly/documentation/issues/1342

**Closed by cldougl** 2019-06-26 15:17 UTC
