### ISSUE TITLE
Plotly3.0 Documentation Upgrade

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#945] opened 2018-06-08 00:04 UTC
This is more of a to-do list//discussion for tackling the documentation that will need to be changed in the plotly.py docs for Jon's Ipyplotly PR https://github.com/plotly/plotly.py/pull/942 Please comment with your suggestions/ideas:

I will be going through all the python docs and seeing if the code examples work or not (and taking note). Then for the failed examples we will:
- rewrite the examples with new syntax/code
_or_
- if the functionality doesn't exist anymore, provide a message to explain that it's 3.0

What do y'all think of this? It would be awesome to have this finished before the end of next week for the presentation.

cc @jackparmer @chriddyp @jmmease @cldougl @bcdunbar 

🔴 == tested with branch, _not_ with `3.0.0rcX`
**Docs Reviewed:**
- [X] fundamentals 
- [X] basic
- [X] statistical 🔴
- [X] scientific 🔴
- [x] financial
- [x] maps
- [x] 3d charts
- [x] multiple axes
- [x] transforms
- [x] add custom controls
- [x] animations
- [x] style options
- [x] layout options
- [x] connecting to databases
- [x] report generation
- [x] add custom controls with JavaScript
- [x] Mathematics
- [x] Statistics
- [x] Peak Analysis
- [x] Signal Analysis

---

**Additional Processes to Tested**
- [x] sign in with `py.sign_in()`
- [ ] onprem sign in and domain setting
- [ ] onprem streaming

---
**Additional Environments Checked**
- [x] macOS
- [x] windows
- [x] chrome
- [x] firefox
- [ ] safari
- [x] edge Microsoft Edge 42.17134.1.0
- [ ] ie

**Comment by Kully** [comment] 2018-06-08 13:58
In Python 2.7:

### Docs that Fail and Why:
https://plot.ly/python/line-and-scatter/#scatter-with-a-color-dimension `size -> int`
```
import plotly.graph_objs as go
import plotly.plotly as py

import numpy as np

trace1 = go.Scatter(
    y = np.random.randn(500),
    mode='markers',
    marker=dict(
        size='16',
        color = np.random.randn(500), #set color equal to a variable
        colorscale='Viridis',
        showscale=True
    )
)
data = [trace1]

py.iplot(data, filename='scatter-plot-with-colorscale')
```

**Comment by jmmease** [comment] 2018-06-11 19:05
The heatmap `z` coordinate as multi-dimensional array should be fixed in https://github.com/plotly/plotly.py/pull/942/commits/ea6cb8544d4fa127468a73ae8340cc4de5568040

**Comment by cldougl** [comment] 2018-06-12 20:38
@kully I've removed the size/int issue from your list and updated the doc :) 
That's more of a typo in the example as that size attribute should only be a int (not a string):  https://plot.ly/python/reference/#scatter-marker-size

**Comment by cldougl** [comment] 2018-06-12 20:49
@Kully I think it would be more helpful to fix the doc or create a new issue when it is broken due to general python 3 incompatibility or other sorts of typos and keep this log focused around issues due to the plotly.py3 release as noted in your [first comment](https://github.com/plotly/documentation/issues/945#issue-330476050):
>This is more of a to-do list//discussion for tackling the documentation that will need to be changed in the plotly.py docs for Jon's Ipyplotly PR plotly/plotly.py#942

**Comment by bcdunbar** [comment] 2018-06-13 07:09
**Note**: I only ran these with `3.0.0rc3`. Will rerun with `3.0.0rc5` then update above comment.

#### Maps

- https://plot.ly/python/choropleth-maps/#united-states-choropleth-map
- https://plot.ly/python/choropleth-maps/#choropleth-inset-map

Both have `ValueError: Invalid value of type 'pandas.core.series.Series'`

- https://plot.ly/python/choropleth-maps/#full-county-choropleths

`AttributeError: 'NoneType' object has no attribute 'inf'`

#### Mapbox (any mapbox tutorial)

- https://plot.ly/python/scattermapbox/#basic-example
- https://plot.ly/python/scattermapbox/#multiple-markers
- https://plot.ly/python/scattermapbox/#nuclear-waste-sites-on-campuses
- https://plot.ly/python/mapbox-county-choropleth/
- https://plot.ly/python/tesla-supercharging-stations/

`AttributeError: 'Layout' object has no attribute 'get'`

**Comment by jmmease** [comment] 2018-06-13 10:44
Thanks for the reports @bcdunbar, I think all of these should be fixed when we push out an rc5 later this morning.

@Kully I haven't been able to exactly reproduce the `DateTimeIndex` errors mentioned above because I get an error from pandas_datareader when I run `web.DataReader` with the `yahoo` data_source.  If the index is a simple `DateTImeIndex` (and not a `MultiIndex`) then I think should also be working in rc5.

**Comment by jmmease** [comment] 2018-06-13 12:55
When you guys go back through with rc5, could you also check that the plots render alright as `FigureWidget`s? 

Basically, whenever there is an `iplot(fig)` command, could you display  `go.FigureWidget(fig)` and make sure it looks the same.  I don't think we're ready to leave these in the documentation, but it would be helpful to flag any errors that crop up this way.

My expectation is that the figure as rendered by `go.FigureWidget` should look identical to `iplot` with the exception that the height may not be the same (which is fine).  I also expect an informative error to be raised when a figure with `frames` is passed to the `go.FigureWidget` constructor.

Thanks!

**Comment by cldougl** [comment] 2018-06-13 20:01
animation with slider issue:
this example: [https://plot.ly/python/animations/#using-a-slider-and-buttons](https://plot.ly/python/animations/#using-a-slider-and-buttons) is not with version 3.0.0.rc9

**Comment by Kully** [comment] 2018-06-15 18:46
> I think it might get a little confusing having that general "broken" list above

ask discussed via our slack convo, and for further clarity for others, I will keep the issues in here that _need to be changed_ before the release. So typo errors such as using `open-circle` (wrong) instead of `circle-open` (true) for example should be fixed before this release.

**Comment by jmmease** [comment] 2018-06-25 23:51
@cldougl Animation with slider issue should be fixed on the `ipyplotly_integration` branch now.

Is there anything else you've found here that I should dig into?

**Comment by cldougl** [comment] 2018-06-28 13:41
@jmmease nothing else from me 🎉

**Comment by Kully** [comment] 2018-08-08 14:46
Shall we close this issue as Plotly 3 is released now?

**Closed** 2018-08-08 14:54 UTC
Labels: Python, enhancement, plotly.py3
