### ISSUE TITLE
Dash R docs /search not working at all

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1672] opened 2020-01-29 18:17 UTC
Algolia is seeing zero queries at all.

cc @rpkyle  :)

**Comment by rpkyle** [comment] 2020-01-29 19:25
@nicolaskruchten I think @cldougl and @KPhans configured this over the summer, but I can confirm that queries are not working at this time.

I wasn't involved with setting this up in July, but if neither of them have bandwidth now, I can help resolve this.

**Comment by nicolaskruchten** [comment] 2020-01-29 19:36
I'll let @jdamiba reach out if he needs help, but let's let him take the lead on fixing it :)

**Comment by rpkyle** [comment] 2020-02-01 02:45
This was fixed by @jdamiba in plotly/dash-docs#769. Closing since the fix is in!

**Closed by rpkyle** 2020-02-01 02:45 UTC
