### ISSUE TITLE
Hover animation issue in docs

### ISSUE THREAD

**Issue by AbdealiJK** [plotly/documentation#1344] opened 2019-05-24 16:41 UTC
Just thought I'd mention it here. If I hover in between two squares it's state is confused
![untitled](https://user-images.githubusercontent.com/2200743/58343514-d49ce600-7e70-11e9-9c10-ed043382ba94.gif)

**Comment by michaelbabyn** [comment] 2019-05-27 14:09
duplicate of #1092

**Closed by michaelbabyn** 2019-05-27 14:09 UTC
