### ISSUE TITLE
Incorrect embed example links

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#277] opened 2016-01-11 22:57 UTC
There's a few issues in this doc: http://help.plot.ly/embed-graphs-in-websites/#options

- The links in the table: **Customizing the iframe** are incorrect (1 link was copied multiple times, those should all be different)
- Just above the table, looks like something is up with 2 images

**Comment by cldougl** [comment] 2016-02-01 18:23
Links should be:
-  https://plot.ly/~Dreamshot/411.embed?autosize=True
- https://plot.ly/~Dreamshot/411.embed?autosize=True&link=false (**important** the f in false has to be lower case)
- https://plot.ly/~Dreamshot/411.embed?autosize=True&modebar=false
- https://plot.ly/~Dreamshot/411.embed?autosize=True&logo=false
- https://plot.ly/~Dreamshot/411.embed?width=100%
- https://plot.ly/~Dreamshot/411.embed?height=650

**Comment by tarzzz** [comment] 2016-02-03 11:31
@cldougl : The issue is for `plotly.github.io` repo, since all the `help.plot.ly` docs are hosted from there.

I have added the issue here: https://github.com/plotly/plotly.github.io/issues/116

Closing..

**Closed by tarzzz** 2016-02-03 11:31 UTC
