### ISSUE TITLE
"barmode" not documented in R-reference

### ISSUE THREAD

**Issue by fabiangehring** [plotly/documentation#488] opened 2016-07-25 08:47 UTC
hi, 
the option "barmode" is not documented in the r-reference even though it's used in the examples (i.e. [here](https://plot.ly/r/bar-charts/ ).

**Comment by cldougl** [comment] 2016-07-28 20:57
Thanks for reporting @fabiangehring 
I'm going to mark it as a duplicate of https://github.com/plotly/documentation/issues/202 but we'll try to get that added in asap. Let us know if you see any other issues in the docs!

**Closed by cldougl** 2016-07-28 20:57 UTC
